export function compactCopy(value: string) {
  return value
    .replace(/새로운 정보를 주지 못합니다/g, '새로운 학습 정보 없음')
    .replace(/만들지 못합니다/g, '생성 불가')
    .replace(/바뀌지 않습니다/g, '변화 없음')
    .replace(/공개할 수 없습니다/g, '공개 불가')
    .replace(/만들 수 없습니다/g, '생성 불가')
    .replace(/비어 있었습니다/g, '미확보')
    .replace(/문제가 있었습니다/g, '문제 발생')
    .replace(/만들었습니다/g, '구축')
    .replace(/늘렸습니다/g, '확대')
    .replace(/줄였습니다/g, '절감')
    .replace(/얻었습니다/g, '도출')
    .replace(/나눴습니다/g, '분리')
    .replace(/흔들렸습니다/g, '불안정')
    .replace(/두었습니다/g, '설정')
    .replace(/어려웠습니다/g, '어려움')
    .replace(/문제였습니다/g, '문제')
    .replace(/되붙입니다/g, '복원')
    .replace(/전파됩니다/g, '전파')
    .replace(/손실됩니다/g, '손실')
    .replace(/낭비됩니다/g, '낭비')
    .replace(/증가시켰습니다/g, '증가')
    .replace(/늘어납니다/g, '증가')
    .replace(/안 됩니다/g, '사용 불가')
    .replace(/큽니다/g, '큼')
    .replace(/해야 했습니다/g, ' 필요')
    .replace(/할 수 없었습니다/g, ' 불가')
    .replace(/할 수 있습니다/g, ' 가능')
    .replace(/수 있었습니다/g, ' 가능')
    .replace(/필요했습니다/g, '필요')
    .replace(/어렵습니다/g, '어려움')
    .replace(/못했습니다/g, '못함')
    .replace(/않았습니다/g, '않음')
    .replace(/않습니다/g, '않음')
    .replace(/없었습니다/g, '없음')
    .replace(/없습니다/g, '없음')
    .replace(/있었습니다/g, '있음')
    .replace(/있습니다/g, '있음')
    .replace(/높았습니다/g, '높음')
    .replace(/컸습니다/g, '큼')
    .replace(/머물렀습니다/g, '머무름')
    .replace(/달라졌습니다/g, '달라짐')
    .replace(/일관됐습니다/g, '일관')
    .replace(/하게 됩니다/g, '함')
    .replace(/됐습니다/g, '됨')
    .replace(/했습니다/g, '')
    .replace(/합니다/g, '')
    .replace(/됩니다/g, '')
    .replace(/입니다/g, '')
    .replace(/\.\s+(?=\S)/g, ' · ')
    .replace(/\.$/, '')
    .replace(/\s{2,}/g, ' ')
    .trim();
}
